### ISSUE TITLE
การใช้ function หา element

### ISSUE THREAD

**Issue by stapy127** [WebIR-Project/moovle-web-crawler#1]
คิดว่าคำสั่งในฟังก์ชั่น extract_links
```python
soup.findAll('a', attrs={'href': re.compile("^http://")})
```
ไม่จำเป็นต้องมี `attrs=...` เพราะเราต้องการทุกลิงค์ไม่ว่าจะเป็น absolute หรือ relative การที่ใส่ให้หาลิงค์ที่มี http:// ขึ้นต้นคงจะไม่ดี

แล้วก็คำสั่ง `.findAll()` คิดว่าควรจะเปลี่ยนเป็น `.find_all()` แทน ซึ่งจริง ๆ มันทำงานเหมือนกัน แต่จะเข้ากับ policy การตั้งชื่อฟังก์ชั่นของ python มากกว่า

**Comment by ekaratst** [comment]
โอเคๆ
